In [2]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

import e_tps as tps

In [4]:
tps.example_run_ising_honeycomb()

Parameters:  {'chi_tps': 2, 'chi_mps': 20, 'J': 1.0, 'g': 1.0, 'N_imaginary': 300, 'N_boundary': 10}
imaginary time evolution
--> delta = 0.1
--> delta = 0.01
--> delta = 0.001
evaluating expectation values


array([-1.66909168])

In [18]:
def run_ising_honeycomb_magnetXZ(g=1., J=1., chi_tps=2, chi_mps=20, N_imaginary=300, N_boundary=10):
    print("Parameters: ", locals())
    model = tps.TFIModelHoneycomb(J, g)
    psi_tps = tps.run_simplified_update(model, chi_tps, N_imaginary)

    d = 2
    Sx, Sz, Id = model.sigmax, model.sigmaz, model.id
    Mx = np.reshape(np.kron(Sx, Id) + np.kron(Id, Sx), (d,d,d,d)) / 3. # per bond (3)
    Mz = np.reshape(np.kron(Sz, Id) + np.kron(Id, Sz), (d,d,d,d)) / 3.
    Mxx = np.reshape(np.kron(Sx, Sx) + np.kron(Sx, Sx), (d,d,d,d)) / 3.
        
    print("evaluating expectation values")
    exp_vals = tps.evaluate_exp_vals(psi_tps, [model.H_bonds, [Mx]*3, [Mz]*3], chi_mps, N_boundary)
    return exp_vals

In [19]:
run_ising_honeycomb_magnetXZ()

Parameters:  {'g': 1.0, 'J': 1.0, 'chi_tps': 2, 'chi_mps': 20, 'N_imaginary': 300, 'N_boundary': 10}
imaginary time evolution
--> delta = 0.1
--> delta = 0.01
--> delta = 0.001
evaluating expectation values


array([-1.66909168, -0.93780195,  0.3432717 ])

In [31]:
%%capture
exp_vals = []
for chitps in range(2,8):
    exp_vals.append(run_ising_honeycomb_magnetXZ(chi_tps=chitps))

In [32]:
exp_vals

[array([-1.66909168, -0.93780195,  0.3432717 ]),
 array([-1.66909174,  0.93780118,  0.34327256]),
 array([-1.66909174, -0.93780104,  0.3432728 ]),
 array([-1.66909174, -0.93780096,  0.34327293]),
 array([-1.66909174, -0.9378009 ,  0.34327306]),
 array([-1.66909174, -0.93780089,  0.34327308])]